# -*- coding: utf-8 -*-
"""Assignment1(18-06-20).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BXwSEQo63xzrqmfarEj4AKMQtb-6-Ksx

write a python to design simple calculator for the operator
"""

a=int(input("enter the value of a"))
b=int(input("enter the value of b"))
print("sum of two numbers is" ,a+b)
print("difference of two numbers",a-b)
print("product of the two numbers",a*b)
print("division of two numbers is",a/b)
print("modules of two numbers is",a%b)
print("exponent of the number",a**b)
print("floor division",a//b)

"""write the python for simple interest"""

p=int(input("enter the value of p"))
t=int(input("enter the time"))
r=int(input("enter the r"))
print("simple interest is",(p*t*r)/100)
p='principal value'
t='time'
r='interest rate'

"""write the python program to calculate area of circle"""

r="radius"
r=int(input("enter the value of r"))
print("area of the circle",3.14*r**2)

"""write the python program for to calculate area of triangle"""

b='breadth'
l='length'
b=int(input("enter the value of b"))
l=int(input("enter the value of l"))
print("area of triangle is",0.5*b*1)

"""write the python programe to temperaturein celsius to fahrenheit"""

c="celsius temperature"
c=float(input("enter thevalue of c"))
fahrenheit=(1.8*c+32)
print("celsius to fahrenheit is",fahrenheit)

"""write a python program to calcualate the area of rectangle"""

l="length"
b="breadth"
l=int(input("enter the value of l"))
b=int(input("enter the value of b"))
print("area of rectangle is",l*b)

"""write a python program to calcualate perimeter osf square"""

a="side of square"
a=int(input("enter the value of a"))
print("perimeter of square is",4*a)

"""write a python program to calculate circumference of a circle"""

r="radius of circle"
r=int(input("enter the value of r"))
print("circumferece of circle is",2*3.14*r)

"""write a python program to swap"""

x=int(input("enter the value of x"))
y=int(input("enter the value of y"))
temp='x'
x='y'
y='temp'
print("the value of x after swapping",x)
print("the value of y after swapping",y)

